### ISSUE TITLE
Find a name

### ISSUE THREAD

**Issue by PiotrFLEURY** [XPEHO/MobileOne#86]
We must find a name for this app.

Please add suggestions in comments.

**Comment by zohra051** [comment]
Simp'Liste :)

**Comment by PiotrFLEURY** [comment]
Share list

**Comment by nathanvandeperre97** [comment]
Shary

**Comment by PiotrFLEURY** [comment]
omelette

**Comment by NayMak** [comment]
Shoppix (mélange de "shopping" et "Xepho")

**Comment by NayMak** [comment]
Listix (mélange de "liste" et "Xpeho")

**Comment by NayMak** [comment]
Shoppix (mélange de "shopping" et "Xepho")

**Comment by NayMak** [comment]
Et enfin, mon favoris personnellement : Shopeo ! Ou peut-être plutôt "Shoppeo", c'est plus joli (également un mélange de "shopping" et "Xpeho")

**Comment by zohra051** [comment]
Les propositions de Didier : Kaba et Mercado :)

**Comment by PiotrFLEURY** [comment]
tote comme les tote bag

**Comment by zohra051** [comment]
En compléments à Piotr : Tot'Sha ? Tote + Share.  ou ToteSha ?

**Comment by PiotrFLEURY** [comment]
Shopette

**Comment by PiotrFLEURY** [comment]
ShoppyAllow

**Comment by PiotrFLEURY** [comment]
> En compléments à Piotr : Tot'Sha ? Tote + Share.  ou ToteSha ? 

Tot'Us

**Comment by zohra051** [comment]
Takashare ? qui signifie : Tu n'as qu'à partager

**Comment by PiotrFLEURY** [comment]
Popositions de Kahina: Weeklyst, Sharelist

**Comment by PiotrFLEURY** [comment]
Simp'Liste won this game.
